=== rosicrucian-dev/botatoolbox/content/data/chakras.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "planet": {
        "type": "string"
      },
      "angel": {
        "type": "string"
      },
      "metal": {
        "type": "string"
      },
      "chakra": {
        "type": "string"
      }
    },
    "required": [
      "planet",
      "angel",
      "metal",
      "chakra"
    ],
    "additionalProperties": false
  }
}

=== rosicrucian-dev/botatoolbox/content/data/chakras.json
[
  {
    "planet": "saturn",
    "angel": "Tsaphkiel",
    "metal": "Lead",
    "chakra": "Center at base of spine"
  },
  {
    "planet": "mars",
    "angel": "Kamael",
    "metal": "Iron",
    "chakra": "Center below navel"
  },
  {
    "planet": "jupiter",
    "angel": "Tzadkiel",
    "metal": "Tin",
    "chakra": "Solar plexus"
  },
  {
    "planet": "sun",
    "angel": "Michael",
    "metal": "Gold",
    "chakra": "Heart center"
  },
  {
    "planet": "venus",
    "angel": "Anael",
    "metal": "Copper",
    "chakra": "Throat center"
  },
  {
    "planet": "moon",
    "angel": "Gabriel",
    "metal": "Silver",
    "chakra": "Pituitary gland"
  },
  {
    "planet": "mercury",
    "angel": "Raphael",
    "metal": "Quicksilver",
    "chakra": "Cerebrum and pineal body"
  }
]
