=== rosicrucian-dev/botatoolbox/content/data/elements.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "slug": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "quality": {
        "type": "string"
      },
      "relatingTo": {
        "type": "string"
      },
      "spirit": {
        "type": "string"
      },
      "kerub": {
        "type": "string"
      }
    },
    "required": [
      "slug",
      "name",
      "quality",
      "relatingTo",
      "spirit",
      "kerub"
    ],
    "additionalProperties": false
  }
}

=== rosicrucian-dev/botatoolbox/content/data/elements.json
[
  {
    "slug": "fire",
    "name": "Fire",
    "quality": "Heat & Dryness",
    "relatingTo": "Radiant energy",
    "spirit": "Salamanders",
    "kerub": "Leo"
  },
  {
    "slug": "water",
    "name": "Water",
    "quality": "Cold & Moisture",
    "relatingTo": "Fluids",
    "spirit": "Undines",
    "kerub": "Scorpio"
  },
  {
    "slug": "air",
    "name": "Air",
    "quality": "Heat & Moisture",
    "relatingTo": "Gases",
    "spirit": "Sylphs",
    "kerub": "Aquarius"
  },
  {
    "slug": "earth",
    "name": "Earth",
    "quality": "Cold & Dryness",
    "relatingTo": "Solids",
    "spirit": "Gnomes",
    "kerub": "Taurus"
  }
]
