=== rosicrucian-dev/botatoolbox/content/data/four-worlds.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "slug": {
        "type": "string"
      },
      "world": {
        "type": "string"
      },
      "principle": {
        "type": "string"
      },
      "beings": {
        "type": "string"
      }
    },
    "required": [
      "slug",
      "world",
      "principle",
      "beings"
    ],
    "additionalProperties": false
  }
}

=== rosicrucian-dev/botatoolbox/content/data/four-worlds.json
[
  {
    "slug": "atziluth",
    "world": "Atziluth",
    "principle": "Archetypal",
    "beings": "Deity"
  },
  {
    "slug": "briah",
    "world": "Briah",
    "principle": "Creative",
    "beings": "Archangelic"
  },
  {
    "slug": "yetzirah",
    "world": "Yetzirah",
    "principle": "Formative",
    "beings": "Angelic"
  },
  {
    "slug": "assiah",
    "world": "Assiah",
    "principle": "Material",
    "beings": "Action, Man, matter, shells & demons"
  }
]
