=== rosicrucian-dev/botatoolbox/content/data/suit-correspondences.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "tarot": {
        "type": "string"
      },
      "playingCard": {
        "type": "string"
      },
      "world": {
        "type": "string"
      },
      "element": {
        "type": "string"
      },
      "letter": {
        "type": "string"
      }
    },
    "required": [
      "tarot",
      "playingCard",
      "world",
      "element",
      "letter"
    ],
    "additionalProperties": false
  }
}

=== rosicrucian-dev/botatoolbox/content/data/suit-correspondences.json
[
  {
    "tarot": "Wands (Scepters)",
    "playingCard": "Clubs",
    "world": "Atziluth",
    "element": "Fire",
    "letter": "Yod"
  },
  {
    "tarot": "Cups (Chalices)",
    "playingCard": "Hearts",
    "world": "Briah",
    "element": "Water",
    "letter": "Heh"
  },
  {
    "tarot": "Swords",
    "playingCard": "Spades",
    "world": "Yetzirah",
    "element": "Air",
    "letter": "Vav"
  },
  {
    "tarot": "Pentacles (Coins)",
    "playingCard": "Diamonds",
    "world": "Assiah",
    "element": "Earth",
    "letter": "Heh"
  }
]
