=== rosicrucian-dev/botatoolbox/content/data/tarot.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "num": {
        "type": "number"
      },
      "name": {
        "type": "string"
      },
      "mobileTitle": {
        "type": "string"
      },
      "slug": {
        "type": "string"
      },
      "letter": {
        "type": "string"
      },
      "english": {
        "type": "string"
      },
      "path": {
        "type": "integer",
        "minimum": 11,
        "maximum": 32
      },
      "significance": {
        "type": "string"
      },
      "astrology": {
        "type": "string"
      },
      "color": {
        "type": "string"
      },
      "note": {
        "type": "string"
      },
      "gematria": {
        "type": "number"
      },
      "alchemy": {
        "type": "string"
      },
      "intelligence": {
        "type": "string"
      },
      "power": {
        "type": "string"
      },
      "human": {
        "type": "string"
      }
    },
    "required": [
      "num",
      "name",
      "slug",
      "letter",
      "english",
      "path",
      "significance",
      "astrology",
      "color",
      "note",
      "gematria",
      "alchemy",
      "intelligence",
      "power",
      "human"
    ],
    "additionalProperties": false
  }
}

=== rosicrucian-dev/botatoolbox/content/data/de/tarot.json
[
  {
    "num": 0,
    "name": "The Fool",
    "slug": "the-fool",
    "letter": "Aleph",
    "english": "A",
    "path": 11,
    "significance": "Ox or Bull",
    "astrology": "Uranus",
    "color": "Yellow",
    "note": "E",
    "gematria": 1,
    "alchemy": "Air",
    "intelligence": "Fiery or Scintillating Intelligence",
    "power": "Life Breath",
    "human": "Life Breath"
  },
  {
    "num": 1,
    "name": "Der Magier",
    "slug": "the-magician",
    "letter": "Beth",
    "english": "B",
    "path": 12,
    "significance": "House",
    "astrology": "Mercury",
    "color": "Yellow",
    "note": "E",
    "gematria": 2,
    "alchemy": "Mercury",
    "intelligence": "The Transparent Intelligence",
    "power": "Aufmerksamkeit",
    "human": "Life and Death"
  },
  {
    "num": 2,
    "name": "The High Priestess",
    "mobileTitle": "High Priestess",
    "slug": "high-priestess",
    "letter": "Gimel",
    "english": "G",
    "path": 13,
    "significance": "Camel",
    "astrology": "Moon",
    "color": "Blue",
    "note": "G#",
    "gematria": 3,
    "alchemy": "Silver",
    "intelligence": "The Uniting Intelligence",
    "power": "Memory",
    "human": "Peace & Strife"
  },
  {
    "num": 3,
    "name": "The Empress",
    "slug": "the-empress",
    "letter": "Daleth",
    "english": "D",
    "path": 14,
    "significance": "Door",
    "astrology": "Venus",
    "color": "Green",
    "note": "F#",
    "gematria": 4,
    "alchemy": "Copper",
    "intelligence": "The Luminous Intelligence",
    "power": "Imagination",
    "human": "Wisdom and Folly (Knowledge and Ignorance)"
  },
  {
    "num": 4,
    "name": "The Emperor",
    "slug": "the-emperor",
    "letter": "Heh",
    "english": "H",
    "path": 15,
    "significance": "Window",
    "astrology": "Aries",
    "color": "Red",
    "note": "C",
    "gematria": 5,
    "alchemy": "Fiery",
    "intelligence": "The Constituting Intelligence",
    "power": "Reason",
    "human": "Sight"
  },
  {
    "num": 5,
    "name": "The Hierophant",
    "slug": "the-hierophant",
    "letter": "Vav",
    "english": "V",
    "path": 16,
    "significance": "Hook or Nail",
    "astrology": "Taurus",
    "color": "Red-Orange",
    "note": "C#",
    "gematria": 6,
    "alchemy": "Earthy",
    "intelligence": "The Triumphant and Eternal Intelligence",
    "power": "Intuition",
    "human": "Hearing"
  },
  {
    "num": 6,
    "name": "The Lovers",
    "slug": "the-lovers",
    "letter": "Zain",
    "english": "Z",
    "path": 17,
    "significance": "Sword",
    "astrology": "Gemini",
    "color": "Orange",
    "note": "D",
    "gematria": 7,
    "alchemy": "Airy",
    "intelligence": "The Disposing Intelligence",
    "power": "Discrimination",
    "human": "Smell"
  },
  {
    "num": 7,
    "name": "The Chariot",
    "slug": "the-chariot",
    "letter": "Cheth",
    "english": "Ch",
    "path": 18,
    "significance": "Fence",
    "astrology": "Cancer",
    "color": "Orange-Yellow",
    "note": "D#",
    "gematria": 8,
    "alchemy": "Watery",
    "intelligence": "The Intelligence of the House of Influence",
    "power": "Receptivity to Divine Will",
    "human": "Speech"
  },
  {
    "num": 8,
    "name": "Strength",
    "slug": "strength",
    "letter": "Teth",
    "english": "T",
    "path": 19,
    "significance": "Serpent",
    "astrology": "Leo",
    "color": "Yellow",
    "note": "E",
    "gematria": 9,
    "alchemy": "Fiery",
    "intelligence": "The Intelligence of the Secret of all Spiritual Activities",
    "power": "The Law of Suggestion",
    "human": "Taste or Digestion"
  },
  {
    "num": 9,
    "name": "The Hermit",
    "slug": "the-hermit",
    "letter": "Yod",
    "english": "I",
    "path": 20,
    "significance": "Open or Creative Hand",
    "astrology": "Virgo",
    "color": "Yellow-Green",
    "note": "F",
    "gematria": 10,
    "alchemy": "Earthy",
    "intelligence": "The Intelligence of Will",
    "power": "The Law of Response",
    "human": "Coition or Touch"
  },
  {
    "num": 10,
    "name": "The Wheel of Fortune",
    "mobileTitle": "Wheel of Fortune",
    "slug": "the-wheel-of-fortune",
    "letter": "Kaph",
    "english": "K",
    "path": 21,
    "significance": "Closed or Grasping Hand",
    "astrology": "Jupiter",
    "color": "Violet",
    "note": "A#",
    "gematria": 20,
    "alchemy": "Tin",
    "intelligence": "The Conciliating or Rewarding Intelligence of Those Who Seek",
    "power": "The Law of Rotation",
    "human": "Wealth and Poverty"
  },
  {
    "num": 11,
    "name": "Justice",
    "slug": "justice",
    "letter": "Lamed",
    "english": "L",
    "path": 22,
    "significance": "Ox-goad",
    "astrology": "Libra",
    "color": "Green",
    "note": "F#",
    "gematria": 30,
    "alchemy": "Airy",
    "intelligence": "The Faithful Intelligence",
    "power": "The Law of Equilibrium",
    "human": "Action"
  },
  {
    "num": 12,
    "name": "The Hanged Man",
    "slug": "the-hanged-man",
    "letter": "Mem",
    "english": "M",
    "path": 23,
    "significance": "Water",
    "astrology": "Neptune",
    "color": "Blue",
    "note": "G#",
    "gematria": 40,
    "alchemy": "Water",
    "intelligence": "The Stable Intelligence",
    "power": "The Law of Reversal",
    "human": "Surrender"
  },
  {
    "num": 13,
    "name": "Death",
    "slug": "death",
    "letter": "Nun",
    "english": "N",
    "path": 24,
    "significance": "Fish",
    "astrology": "Scorpio",
    "color": "Green-Blue",
    "note": "G",
    "gematria": 50,
    "alchemy": "Watery",
    "intelligence": "The Imaginative Intelligence",
    "power": "The Law of Transformation",
    "human": "Motion"
  },
  {
    "num": 14,
    "name": "Temperance",
    "slug": "temperance",
    "letter": "Samekh",
    "english": "S",
    "path": 25,
    "significance": "Prop or Support",
    "astrology": "Sagittarius",
    "color": "Blue",
    "note": "G#",
    "gematria": 60,
    "alchemy": "Fiery",
    "intelligence": "The Intelligence of Probation or Trial",
    "power": "The Law of Probation",
    "human": "Wrath"
  },
  {
    "num": 15,
    "name": "The Devil",
    "slug": "the-devil",
    "letter": "Ayin",
    "english": "O",
    "path": 26,
    "significance": "Eye",
    "astrology": "Capricorn",
    "color": "Blue-Violet",
    "note": "A",
    "gematria": 70,
    "alchemy": "Earthy",
    "intelligence": "The Renewing Intelligence",
    "power": "Bondage",
    "human": "Laughter"
  },
  {
    "num": 16,
    "name": "The Tower",
    "slug": "the-tower",
    "letter": "Peh",
    "english": "P",
    "path": 27,
    "significance": "Mouth",
    "astrology": "Mars",
    "color": "Red",
    "note": "C",
    "gematria": 80,
    "alchemy": "Iron",
    "intelligence": "The Exciting Intelligence",
    "power": "Awakening",
    "human": "Beauty and Ugliness (Grace and Sin)"
  },
  {
    "num": 17,
    "name": "The Star",
    "slug": "the-star",
    "letter": "Tzaddi",
    "english": "Tz",
    "path": 28,
    "significance": "Fish-hook",
    "astrology": "Aquarius",
    "color": "Violet",
    "note": "A#",
    "gematria": 90,
    "alchemy": "Airy",
    "intelligence": "The Natural Intelligence",
    "power": "Revelation",
    "human": "Meditation"
  },
  {
    "num": 18,
    "name": "The Moon",
    "slug": "the-moon",
    "letter": "Qoph",
    "english": "Q",
    "path": 29,
    "significance": "Back of Head",
    "astrology": "Pisces",
    "color": "Violet-Red",
    "note": "B",
    "gematria": 100,
    "alchemy": "Watery",
    "intelligence": "The Corporeal Intelligence",
    "power": "Organization",
    "human": "Sleep"
  },
  {
    "num": 19,
    "name": "The Sun",
    "slug": "the-sun",
    "letter": "Resh",
    "english": "R",
    "path": 30,
    "significance": "Front of Head (Face)",
    "astrology": "Sun",
    "color": "Orange",
    "note": "D",
    "gematria": 200,
    "alchemy": "Gold",
    "intelligence": "The Collecting Intelligence",
    "power": "Regeneration",
    "human": "Fertility & Sterility"
  },
  {
    "num": 20,
    "name": "Judgement",
    "slug": "judgement",
    "letter": "Shin",
    "english": "Sh",
    "path": 31,
    "significance": "Tooth or Fang",
    "astrology": "Pluto",
    "color": "Red",
    "note": "C",
    "gematria": 300,
    "alchemy": "Fire",
    "intelligence": "The Perpetual Intelligence",
    "power": "Realization",
    "human": "Decision"
  },
  {
    "num": 21,
    "name": "The World",
    "slug": "the-world",
    "letter": "Tav",
    "english": "Th",
    "path": 32,
    "significance": "Mark or Cross",
    "astrology": "Saturn",
    "color": "Blue-Violet",
    "note": "A",
    "gematria": 400,
    "alchemy": "Lead",
    "intelligence": "The Administrative Intelligence",
    "power": "Cosmic Consciousness",
    "human": "Dominion and Slavery"
  }
]
